<script lang="ts">
  import { onMount, tick } from "svelte";
  import { clearAlertMute, clearHistory, exportHistory, getAutostart, getHistoryPersistenceError, getSettings, sendTestNotification, setAutostart, updateSetting } from "../../ipc/settings";
  import type { SettingsFocusTarget, SettingsSnapshot } from "../../ipc/types";
  import { openExternal } from "../../ipc/dashboard";
  let { close, focusTarget=null }:{close:()=>void;focusTarget?:SettingsFocusTarget}=$props();
  let settings=$state<SettingsSnapshot|null>(null), autostart=$state(false), error=$state<string|null>(null), testSent=$state(false), dataMessage=$state<string|null>(null), now=$state(Date.now());
  const rules:Record<string,string>={"realm-status":"Realm status","local-record":"Local records","population-threshold":"Population threshold","token-price-above":"Price above","token-price-below":"Price below","token-change-gain":"Market gain","token-change-loss":"Market loss","game-release":"Game releases"};
  const minuteValue=(minute:number)=>`${String(Math.floor(minute/60)).padStart(2,"0")}:${String(minute%60).padStart(2,"0")}`;
  const timeMinute=(value:string)=>{const [h,m]=value.split(":").map(Number);return h*60+m};
  const activeMutes=$derived(settings?Object.entries(settings.advancedAlertMutes).filter(([,until])=>until>now/1000):[]);
  async function set(key:keyof SettingsSnapshot,value:unknown){if(!settings)return; const before=settings;settings={...settings,[key]:value};error=null;try{settings=await updateSetting(key,value)}catch(e){settings=before;error=String(e)}}
  async function toggleAutostart(enabled:boolean){const before=autostart;autostart=enabled;try{autostart=await setAutostart(enabled)}catch(e){autostart=before;error=String(e)}}
  async function unmute(ruleId:string){try{settings=await clearAlertMute(ruleId)}catch(e){error=String(e)}}
  async function test(){try{await sendTestNotification();testSent=true}catch(e){error=String(e)}}
  async function exportData(format:"csv"|"json"){error=null;dataMessage=null;try{if(await exportHistory(format))dataMessage=`History exported as ${format.toUpperCase()}.`}catch(e){error=String(e)}}
  async function clearData(){if(!confirm("Clear all local player history and the all-time peak? This cannot be undone."))return;error=null;dataMessage=null;try{settings=await clearHistory();dataMessage="Local history and peak cleared."}catch(e){error=String(e)}}
  onMount(()=>{let disposed=false;const timer=window.setInterval(async()=>{now=Date.now();const value=await getHistoryPersistenceError().catch(()=>null);if(!disposed&&value)error=value},2000);void (async()=>{try{let persistenceError;[settings,autostart,persistenceError]=await Promise.all([getSettings(),getAutostart(),getHistoryPersistenceError()]);if(persistenceError)error=persistenceError;await tick();if(focusTarget){const target=document.querySelector<HTMLElement>(`[data-focus="${focusTarget}"]`);if(target){target.tabIndex=-1;target.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"center"});target.focus({preventScroll:true});target.classList.add("focus-target");window.setTimeout(()=>target.classList.remove("focus-target"),1800)}}}catch(e){error=String(e)}})();return()=>{disposed=true;clearInterval(timer)}});
</script>

<section class="panel" aria-label="Settings">
 <header><button class="back glass-button" onclick={close} aria-label="Back to dashboard"><span aria-hidden="true">‹</span></button><h1>SETTINGS</h1></header>
 <div class="scroll">
  {#if !settings}<p class="loading">Loading settings…</p>{:else}
   <article data-focus="appearance"><h2>▣ Appearance</h2><label>Panel display<select value={settings.menuBarDisplayMode} onchange={(e)=>set("menuBarDisplayMode",e.currentTarget.value)}><option value="playersAndChange">Players + WOC</option><option value="full">Full</option><option value="players">Players</option><option value="token">Token</option><option value="iconOnly">Icon only</option></select></label></article>
   <article><h2>↻ General</h2><label>Player refresh<select value={settings.pollSeconds} onchange={(e)=>set("pollSeconds",Number(e.currentTarget.value))}><option value="10">10 seconds</option><option value="30">30 seconds</option><option value="60">1 minute</option><option value="300">5 minutes</option></select></label><label>Token refresh<select value={settings.cryptoPollSeconds} onchange={(e)=>set("cryptoPollSeconds",Number(e.currentTarget.value))}><option value="30">30 seconds</option><option value="60">1 minute</option><option value="300">5 minutes</option><option value="900">15 minutes</option></select></label></article>
   <article><h2>● Notifications</h2><p>Choose the events WoC can notify you about.</p><label class="toggle"><span>Realm up and down</span><input type="checkbox" checked={settings.alertsEnabled} onchange={(e)=>set("alertsEnabled",e.currentTarget.checked)}/></label><label class="toggle"><span>New local records</span><input type="checkbox" checked={settings.peakAlertsEnabled} onchange={(e)=>set("peakAlertsEnabled",e.currentTarget.checked)}/></label><div data-focus="population"><label class="toggle"><span>Population alert</span><input type="checkbox" checked={settings.populationThresholdAlertsEnabled} onchange={(e)=>set("populationThresholdAlertsEnabled",e.currentTarget.checked)}/></label>{#if settings.populationThresholdAlertsEnabled}<label>At least <input class="number" type="number" min="1" max="10000" step="5" value={settings.populationAlertThreshold} onchange={(e)=>set("populationAlertThreshold",Math.min(10000,Math.max(1,Number(e.currentTarget.value))))}/></label>{/if}</div><label class="toggle" data-focus="release-alerts"><span>New game releases</span><input type="checkbox" checked={settings.releaseAlertsEnabled} onchange={(e)=>set("releaseAlertsEnabled",e.currentTarget.checked)}/></label><button class="action" onclick={test}>Send test notification</button>{#if testSent}<span class="success">Notification requested</span>{/if}<label>Cooldown<select value={settings.advancedAlertCooldown} onchange={(e)=>set("advancedAlertCooldown",Number(e.currentTarget.value))}><option value="0">Off</option><option value="900">15 minutes</option><option value="3600">1 hour</option><option value="14400">4 hours</option><option value="86400">1 day</option></select></label><label class="toggle"><span>Quiet hours</span><input type="checkbox" checked={settings.advancedAlertQuietHoursEnabled} onchange={(e)=>set("advancedAlertQuietHoursEnabled",e.currentTarget.checked)}/></label>{#if settings.advancedAlertQuietHoursEnabled}<div class="times"><label>From<input type="time" value={minuteValue(settings.advancedAlertQuietStartMinute)} onchange={(e)=>set("advancedAlertQuietStartMinute",timeMinute(e.currentTarget.value))}/></label><label>To<input type="time" value={minuteValue(settings.advancedAlertQuietEndMinute)} onchange={(e)=>set("advancedAlertQuietEndMinute",timeMinute(e.currentTarget.value))}/></label></div>{/if}{#if activeMutes.length}<h3>ACTIVE MUTES</h3>{#each activeMutes as [id,until]}<div class="mute"><span>{rules[id]??id}<small>Until {new Date(until*1000).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</small></span><button onclick={()=>unmute(id)}>Unmute</button></div>{/each}{/if}</article>
   <article data-focus="market-move"><h2>⌁ $WOC Alerts</h2><label class="toggle"><span>Rolling price moves</span><input type="checkbox" checked={settings.cryptoAlertsEnabled} onchange={(e)=>set("cryptoAlertsEnabled",e.currentTarget.checked)}/></label>{#if settings.cryptoAlertsEnabled}<div class="split"><label class="toggle"><span>Gains</span><input type="checkbox" checked={settings.tokenChangeGainAlertsEnabled} onchange={(e)=>set("tokenChangeGainAlertsEnabled",e.currentTarget.checked)}/></label><label class="toggle"><span>Losses</span><input type="checkbox" checked={settings.tokenChangeLossAlertsEnabled} onchange={(e)=>set("tokenChangeLossAlertsEnabled",e.currentTarget.checked)}/></label></div><label>Window<select value={settings.cryptoAlertWindow} onchange={(e)=>set("cryptoAlertWindow",e.currentTarget.value)}><option value="oneHour">1 hour</option><option value="sixHours">6 hours</option><option value="twentyFourHours">24 hours</option></select></label><label>Threshold <b>{settings.cryptoAlertThreshold}%</b><input class="range" type="range" min="1" max="50" step="1" value={settings.cryptoAlertThreshold} oninput={(e)=>set("cryptoAlertThreshold",Number(e.currentTarget.value))}/></label>{/if}<hr/><label class="toggle"><span>Price above</span><input type="checkbox" checked={settings.tokenPriceAboveAlertsEnabled} onchange={(e)=>set("tokenPriceAboveAlertsEnabled",e.currentTarget.checked)}/></label>{#if settings.tokenPriceAboveAlertsEnabled}<label>$ <input class="price" value={settings.tokenPriceAboveTarget} onblur={(e)=>set("tokenPriceAboveTarget",Math.min(1e6,Math.max(1e-12,Number(e.currentTarget.value)||.001)))}/></label>{/if}<label class="toggle"><span>Price below</span><input type="checkbox" checked={settings.tokenPriceBelowAlertsEnabled} onchange={(e)=>set("tokenPriceBelowAlertsEnabled",e.currentTarget.checked)}/></label>{#if settings.tokenPriceBelowAlertsEnabled}<label>$ <input class="price" value={settings.tokenPriceBelowTarget} onblur={(e)=>set("tokenPriceBelowTarget",Math.min(1e6,Math.max(1e-12,Number(e.currentTarget.value)||.00025)))}/></label>{/if}</article>
   <article><h2>⚙ System</h2><label class="toggle"><span>Launch at login</span><input type="checkbox" checked={autostart} onchange={(e)=>toggleAutostart(e.currentTarget.checked)}/></label><p>Starts WoC automatically for this desktop session.</p></article>
   <article><h2>⌁ Data &amp; Privacy</h2><p>Player history and settings stay on this device. WoC sends no telemetry.</p><div class="data-actions"><button class="action" onclick={()=>exportData("csv")}>Export CSV</button><button class="action" onclick={()=>exportData("json")}>Export JSON</button></div><button class="danger" onclick={clearData}>Clear local history</button>{#if dataMessage}<span class="success" role="status">{dataMessage}</span>{/if}</article>
   <article><h2>ⓘ About</h2><strong>WoC Player Count</strong><p>Version 0.1.0 · Data from World of ClaudeCraft, DEX Screener, and GeckoTerminal.</p><div class="links"><button onclick={()=>openExternal("https://github.com/FernandoX7/woc-widget-linux/blob/main/PRIVACY.md")}>Privacy</button><button onclick={()=>openExternal("https://github.com/FernandoX7/woc-widget-linux/blob/main/LICENSE")}>License</button><button onclick={()=>openExternal("https://github.com/FernandoX7/woc-widget-linux/issues")}>Support</button><button onclick={()=>openExternal("https://github.com/FernandoX7/woc-widget-linux")}>GitHub</button></div></article>
  {/if}
 </div>
 {#if error}<p class="error" role="alert">Couldn’t save: {error}</p>{/if}<footer><span>Settings are saved automatically</span><button onclick={close}>Done</button></footer>
</section>

<style>
 .panel{height:100%;padding:var(--space-16);display:flex;flex-direction:column;gap:var(--space-10)}header{height:28px;display:grid;grid-template-columns:28px 1fr 28px;align-items:center}h1{grid-column:2;margin:0;text-align:center;font-size:11px;letter-spacing:1.8px;background:var(--gradient-brand-horizontal);color:transparent;background-clip:text}.back{width:28px;height:28px;border:1px solid var(--color-card-stroke);border-radius:50%;background:var(--color-glass-fill);font-size:24px;line-height:20px}.scroll{min-height:0;overflow-y:auto;display:flex;flex-direction:column;gap:var(--space-10);padding:var(--space-2) var(--space-2) var(--space-8);scrollbar-width:thin}article{padding:var(--space-12);border:1px solid var(--color-card-stroke);border-radius:var(--radius-14);background:var(--color-card);display:flex;flex-direction:column;gap:9px;transition:border-color var(--motion-hover),box-shadow var(--motion-hover)}article:focus-within,:global(.focus-target){border-color:var(--color-cyan);box-shadow:0 0 0 2px var(--color-cyan-30)}h2{margin:0;color:var(--color-cyan);font-size:11px;letter-spacing:.8px}h3{margin:5px 0 0;color:var(--color-text-tertiary);font-size:10px;letter-spacing:1px}p{margin:0;color:var(--color-text-secondary);font-size:10.5px;line-height:1.35}label,.mute{display:flex;align-items:center;justify-content:space-between;gap:var(--space-10);font-size:12px}.toggle input{accent-color:var(--color-cyan)}select,input[type=time],.number,.price{color:var(--color-text-primary);background:var(--color-pill-opaque);border:1px solid var(--color-card-stroke);border-radius:var(--radius-7);padding:4px var(--space-7)}.number{width:84px}.price{width:120px}.range{width:170px;accent-color:var(--color-cyan)}.split,.times,.links,.data-actions{display:flex;gap:var(--space-8)}.split>*{flex:1}.action,.mute button,.links button,footer button,.danger{border:1px solid var(--color-card-stroke);border-radius:var(--radius-8);background:var(--color-glass-fill);padding:var(--space-6) 9px;transition:background var(--motion-hover),border-color var(--motion-hover)}.action:hover,.mute button:hover,.links button:hover,footer button:hover,.danger:hover,.back:hover{background:var(--color-switcher-selection)}.danger{color:var(--color-red);border-color:color-mix(in srgb,var(--color-red) 45%,transparent)}.success{font-size:10px;color:var(--color-green)}.mute small{display:block;color:var(--color-text-tertiary)}hr{width:100%;border:0;border-top:1px solid var(--color-card-stroke)}footer{display:flex;align-items:center;justify-content:space-between;color:var(--color-text-tertiary);font-size:10.5px}footer button{min-width:90px;background:var(--gradient-brand-diagonal);font-weight:700}.error{color:var(--color-red)}
</style>
