export const strings = {
  realmFallback: "Claudemoon",
  marketFallback: "$WOC —",
  playerCount: (count: number) => `${count} players`,
  online: "online",
  sync: "SYNC",
  offline: "OFFLINE",
  cached: "showing cached",
  live: "LIVE",
  dashboardPages: "Dashboard pages",
  pages: { overview: "Overview", market: "$WOC", community: "Community" },
  overview: {
    chartTitle: "PLAYERS OVER TIME",
    rangePicker: "Player history range",
    coverage: (percent: number) => `${percent}% coverage`,
    emptyHistory: "Gathering player history",
    emptyHistoryHint: "The chart will appear after the first observation.",
    loadingHistory: "Loading player history",
    chartAccessibility: "Players online over time. Use left and right arrow keys to inspect points. Press Escape to clear.",
    chartSummary: (range: string, points: number) =>
      points === 0
        ? `Players online over ${range}. No observations yet. Use left and right arrow keys to inspect points.`
        : `Players online over ${range}. ${points} observations. Use left and right arrow keys to inspect points. Press Escape to clear.`,
    playerTooltip: (count: number) => `${count} players`,
    welcomeTitle: "Welcome to WoC Player Count",
    welcomeBody: "Live realm activity and your local observations, at a glance.",
    dismissWelcome: "Dismiss welcome",
    status: {
      syncTitle: "SYNC",
      syncDetail: "Fetching the latest realm status.",
      offlineTitle: "OFFLINE",
      offlineDetail: "The realm is currently reported offline.",
      cachedTitle: "Showing cached status",
      cachedDetail: "Live realm status is unavailable. The last observation is shown.",
      retry: "Retry",
    },
    stats: {
      shortChange: "30m change",
      todayHigh: "today high",
      localRecord: "local record",
      rangeAverage: "range average",
      unavailable: "—",
    },
    rhythm: {
      title: "REALM RHYTHM",
      percentile: (percent: number) => `Busier than ${percent}% of your observed window`,
      gathering: (sampleCount: number) => `Gathering observations (${sampleCount}/30)`,
      observed: (percent: number) => `${percent}% observed`,
      footnote: "Based only on observations stored locally on this device.",
      alertAt: (threshold: number) => `Alert at ${threshold}`,
      alertSetup: "Configure population alert",
    },
    quickLinks: "Quick links",
    links: { play: "Play", wiki: "Wiki", highScores: "High scores" },
  },
  market: {
    pageLabel: "$WOC market",
    spot: "$WOC SPOT",
    timeframe: "Market timeframe",
    alertAccessibility: (threshold: number, window: string) => `Configure market move alert: ${threshold}% over ${window}`,
    quote: "Quote",
    chart: "Chart",
    retry: "Retry",
    showingCached: "Showing cached data",
    cachedCandles: (interval:string) => `Showing cached ${interval} candles while the new interval loads`,
    cachedMinutes: (minutes: number) => `updated ${minutes}m ago`,
    cachedHours: (hours: number) => `updated ${hours}h ago`,
    unavailableDetail: "Some market data is temporarily unavailable.",
    volume: (timeframe: string) => `${timeframe} volume`,
    liquidity: "Liquidity",
    transactions: (timeframe: string) => `${timeframe} buys / sells`,
    marketCap: "Market cap",
    fdv: "Fully diluted value",
    buyShare: (fraction: number) => `Buys ${Math.round(fraction * 100)}%`,
    sellShare: (fraction: number) => `Sells ${Math.round(fraction * 100)}%`,
    activityAccessibility: (timeframe: string, buys: number, sells: number) => `${timeframe} activity: ${buys} buys and ${sells} sells`,
    view: "View",
    copyContract: "Copy contract",
    contractCopied: "Contract copied",
    dataSource: "Market chart data by GeckoTerminal",
    contract: "3WjLscH2JsXLEFJZRA9z8ti8yRGxWGKbqymPd7UicRth",
    dexUrl: "https://dexscreener.com/solana/5we9yjzpeqxcyl4jn9khjtsr48xzyh47xtar9kg3wy1p",
    geckoUrl: "https://www.geckoterminal.com/solana/pools/5wE9YJzPeQxCYL4jN9KhjTSR48Xzyh47xTAR9kg3wy1p",
    feedStates: { idle:"waiting", loading:"loading", live:"live", cached:"cached", unavailable:"unavailable" },
  },
  community: {
    pageLabel: "Community",
    around: (realm:string) => `AROUND ${realm.toUpperCase()}`,
    accounts: "ACCOUNTS",
    realm: "REALM",
    realms: "REALMS",
    realmType: "REALM TYPE",
    latestRelease: "LATEST RELEASE",
    leaderboard: "LEADERBOARD",
    loading: "Loading community data",
    unavailable: "Community data is unavailable",
    showingCached: "Showing cached data",
    cachedUpdated: (relative:string) => `Showing cached data · updated ${relative}`,
    updatedJustNow: "updated just now",
    updatedSeconds: (seconds:number) => `updated ${seconds}s ago`,
    updatedMinutes: (minutes:number) => `updated ${minutes}m ago`,
    updatedHours: (hours:number) => `updated ${hours}h ago`,
    retry: "Retry",
    noReleases: "No releases yet",
    noRankings: "No rankings yet",
    viewRelease: "View release",
    recentReleases: "Recent releases",
    releaseAlert: "Configure release alerts",
    level: (value:number) => `Level ${value}`,
    xp: (value:string) => `${value} XP`,
    prestige: (value:number) => `Prestige ${value}`,
    links: { discord:"Discord", github:"GitHub", wiki:"Wiki", highScores:"High scores" },
    urls: { discord:"https://discord.com/invite/GjhnUsBtw", github:"https://github.com/levy-street/world-of-claudecraft", wiki:"https://worldofclaudecraft.com/wiki/", highScores:"https://worldofclaudecraft.com/#highscores" },
  },
  placeholders: {
    market: "$WOC content arrives in Phase 11.",
    community: "Community content arrives in Phase 12.",
    settings: "Settings arrive in Phase 13.",
  },
  refresh: "Refresh",
  refreshShortcut: "Refresh (Ctrl+R)",
  settings: "Settings",
  settingsShortcut: "Settings (Ctrl+,)",
  quit: "Quit",
  quitShortcut: "Quit (Ctrl+Q)",
  updatedNever: "not updated yet",
  updatedNow: "updated now",
  updatedSeconds: (seconds: number) => `updated ${seconds}s ago`,
} as const;
